// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.springframework.roo.petclinic.domain.AbstractPerson;
import org.springframework.roo.petclinic.domain.AbstractPerson_Roo_Jaxb_Entity;

privileged aspect AbstractPerson_Roo_Jaxb_Entity {
    
    /*
     * This Aspect takes the lower precedence
     */
    declare precedence: *, AbstractPerson_Roo_Jaxb_Entity;
    
    declare @type: AbstractPerson: @XmlRootElement(name = "abstractperson", namespace = "http://ws.petclinic.roo.springframework.org/");
    
    declare @method: public Long AbstractPerson.getId(): @XmlTransient;
    
    /**
     * Must return an unique ID across all entities
     * 
     * @return String
     */
    @XmlID
    @XmlAttribute(name = "id")
    public String AbstractPerson.getXmlIdentityInfo() {
        return getClass().getName() + ":" + getId();
    }
    
}
