// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain;

import java.util.Date;
import org.springframework.roo.petclinic.domain.AbstractPerson;

privileged aspect AbstractPerson_Roo_JavaBean {
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public Long AbstractPerson.getId() {
        return this.id;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     */
    public void AbstractPerson.setId(Long id) {
        this.id = id;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Integer
     */
    public Integer AbstractPerson.getVersion() {
        return this.version;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param version
     */
    public void AbstractPerson.setVersion(Integer version) {
        this.version = version;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getFirstName() {
        return this.firstName;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param firstName
     */
    public void AbstractPerson.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getLastName() {
        return this.lastName;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param lastName
     */
    public void AbstractPerson.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getAddress() {
        return this.address;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param address
     */
    public void AbstractPerson.setAddress(String address) {
        this.address = address;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getCity() {
        return this.city;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param city
     */
    public void AbstractPerson.setCity(String city) {
        this.city = city;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getTelephone() {
        return this.telephone;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param telephone
     */
    public void AbstractPerson.setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getHomePage() {
        return this.homePage;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param homePage
     */
    public void AbstractPerson.setHomePage(String homePage) {
        this.homePage = homePage;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String AbstractPerson.getEmail() {
        return this.email;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param email
     */
    public void AbstractPerson.setEmail(String email) {
        this.email = email;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Date
     */
    public Date AbstractPerson.getBirthDay() {
        return this.birthDay;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param birthDay
     */
    public void AbstractPerson.setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
    
}
