// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain;

import io.springlets.format.EntityFormat;
import javax.persistence.Entity;
import org.springframework.roo.petclinic.domain.AbstractPerson;

privileged aspect AbstractPerson_Roo_Jpa_Entity {
    
    declare @type: AbstractPerson: @Entity;
    
    declare @type: AbstractPerson: @EntityFormat;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AbstractPerson.ITERABLE_TO_ADD_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AbstractPerson.ITERABLE_TO_REMOVE_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";
    
}
