// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain;

import java.util.Set;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import org.springframework.roo.petclinic.domain.Owner;
import org.springframework.roo.petclinic.domain.Owner_Roo_Jaxb_Entity;
import org.springframework.roo.petclinic.domain.Pet;

privileged aspect Owner_Roo_Jaxb_Entity {
    
    /*
     * This Aspect takes the lower precedence
     */
    declare precedence: *, Owner_Roo_Jaxb_Entity;
    
    declare @type: Owner: @XmlRootElement(name = "owner", namespace = "http://ws.petclinic.roo.springframework.org/");
    
    declare @method: public Set<Pet> Owner.getPets(): @XmlIDREF;
    
    declare @method: public Set<Pet> Owner.getPets(): @XmlElement(name = "pet");
    
    declare @method: public Set<Pet> Owner.getPets(): @XmlElementWrapper(name = "pets");
    
}
