// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain.dod;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import org.springframework.roo.petclinic.domain.Owner;
import org.springframework.roo.petclinic.domain.dod.OwnerFactory;

privileged aspect OwnerFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Owner} with the given index.
     * 
     * @param index position of the Owner
     * @return a new transient Owner
     */
    public Owner OwnerFactory.create(int index) {
        Owner obj = new Owner();
        setAddress(obj, index);
        setBirthDay(obj, index);
        setCity(obj, index);
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setEmail(obj, index);
        setFirstName(obj, index);
        setHomePage(obj, index);
        setLastName(obj, index);
        setModifiedBy(obj, index);
        setModifiedDate(obj, index);
        setTelephone(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setAddress(Owner obj, int index) {
        String address = "address_" + index;
        if (address.length() > 50) {
            address = address.substring(0, 50);
        }
        obj.setAddress(address);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setBirthDay(Owner obj, int index) {
        Date birthDay = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), 
			Calendar.getInstance().get(Calendar.MONTH), 
			Calendar.getInstance().get(Calendar.DAY_OF_MONTH), 
			Calendar.getInstance().get(Calendar.HOUR_OF_DAY), 
			Calendar.getInstance().get(Calendar.MINUTE), 
			Calendar.getInstance().get(Calendar.SECOND) + 
			new Double(Math.random() * 1000).intValue()).getTime();
        obj.setBirthDay(birthDay);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setCity(Owner obj, int index) {
        String city = "city_" + index;
        if (city.length() > 30) {
            city = city.substring(0, 30);
        }
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setCreatedBy(Owner obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setCreatedDate(Owner obj, int index) {
        Calendar createdDate = Calendar.getInstance();
        obj.setCreatedDate(createdDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setEmail(Owner obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 30) {
            email = email.substring(0, 30);
        }
        obj.setEmail(email);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setFirstName(Owner obj, int index) {
        String firstName = "firstName_" + index;
        if (firstName.length() > 30) {
            firstName = firstName.substring(0, 30);
        }
        obj.setFirstName(firstName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setHomePage(Owner obj, int index) {
        String homePage = "homePage_" + index;
        if (homePage.length() > 30) {
            homePage = homePage.substring(0, 30);
        }
        obj.setHomePage(homePage);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setLastName(Owner obj, int index) {
        String lastName = "lastName_" + index;
        if (lastName.length() > 30) {
            lastName = lastName.substring(0, 30);
        }
        obj.setLastName(lastName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setModifiedBy(Owner obj, int index) {
        String modifiedBy = "modifiedBy_" + index;
        obj.setModifiedBy(modifiedBy);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setModifiedDate(Owner obj, int index) {
        Calendar modifiedDate = Calendar.getInstance();
        obj.setModifiedDate(modifiedDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OwnerFactory.setTelephone(Owner obj, int index) {
        String telephone = "telephone_" + index;
        obj.setTelephone(telephone);
    }
    
}
