// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain.dod;

import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.roo.petclinic.domain.dod.VisitDataOnDemand;

privileged aspect VisitDataOnDemand_Roo_Configurable {
    
    declare @type: VisitDataOnDemand: @Configurable;
    
}
