// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the extended .java class if you wish to edit any member(s).
package io.github.jcagarcia.proofs.springroonoaspectjava.service.impl;

import io.github.jcagarcia.proofs.springroonoaspectjava.model.Pet;
import io.github.jcagarcia.proofs.springroonoaspectjava.repository.PetRepository;
import io.github.jcagarcia.proofs.springroonoaspectjava.service.api.PetService;
import io.springlets.data.domain.GlobalSearch;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class PetServiceImpl_ROO implements PetService {

    // DO NOT EDIT THIS CODE. THIS CODE IS MANAGED BY THE
    // @RooServiceImpl ANNOTATION

    /**
     * TODO Auto-generated attribute documentation
     */
    @Autowired
    private PetRepository petRepository;

    /**
     * TODO Auto-generated method documentation
     *
     * @param Pet
     */
    @Transactional
    public void delete(Pet Pet) {
        getPetRepository().delete(Pet);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param entities
     * @return List
     */
    @Transactional
    public List<Pet> save(Iterable<Pet> entities) {
        return getPetRepository().save(entities);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     */
    @Transactional
    public void delete(Iterable<Long> ids) {
        List<Pet> toDelete = getPetRepository().findAll(ids);
        getPetRepository().deleteInBatch(toDelete);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param entity
     * @return Pet
     */
    @Transactional
    public Pet save(Pet entity) {
        return getPetRepository().save(entity);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param id
     * @return Pet
     */
    public Pet findOne(Long id) {
        return getPetRepository().findOne(id);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     * @return List
     */
    public List<Pet> findAll(Iterable<Long> ids) {
        return getPetRepository().findAll(ids);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @return List
     */
    public List<Pet> findAll() {
        return getPetRepository().findAll();
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @return Long
     */
    public long count() {
        return getPetRepository().count();
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Pet> findAll(GlobalSearch globalSearch, Pageable pageable) {
        return getPetRepository().findAll(globalSearch, pageable);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Pet> findAllByIdsIn(List<Long> ids, GlobalSearch globalSearch, Pageable pageable) {
        return getPetRepository().findAllByIdsIn(ids, globalSearch, pageable);
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @return Class
     */
    public Class<Pet> getEntityType() {
        return Pet.class;
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @return Class
     */
    public Class<Long> getIdType() {
        return Long.class;
    }

    /**
     * TODO Auto-generated method documentation
     *
     * @return PetRepository
     */
    public PetRepository getPetRepository() {
        return petRepository;
    }

}
