// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.repository;

import static org.assertj.core.api.Assertions.assertThat;

import io.springlets.data.domain.GlobalSearch;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.roo.petclinic.config.SpringDataJpaDetachableRepositoryConfiguration;
import org.springframework.roo.petclinic.dod.DataOnDemandConfiguration;
import org.springframework.roo.petclinic.domain.Pet;
import org.springframework.roo.petclinic.domain.dod.PetDataOnDemand;
import org.springframework.roo.petclinic.repository.PetRepository;
import org.springframework.roo.petclinic.repository.PetRepositoryIT;
import org.springframework.test.context.junit4.SpringRunner;

privileged aspect PetRepositoryIT_Roo_RepositoryJpaIntegrationTest {
    
    declare @type: PetRepositoryIT: @RunWith(SpringRunner.class);
    
    declare @type: PetRepositoryIT: @DataJpaTest;
    
    declare @type: PetRepositoryIT: @Import({ DataOnDemandConfiguration.class, SpringDataJpaDetachableRepositoryConfiguration.class });
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Rule
    public ExpectedException PetRepositoryIT.thrown = ExpectedException.none();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private PetRepository PetRepositoryIT.repository;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private PetDataOnDemand PetRepositoryIT.dod;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetRepository
     */
    public PetRepository PetRepositoryIT.getRepository() {
        return repository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetDataOnDemand
     */
    public PetDataOnDemand PetRepositoryIT.getDod() {
        return dod;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Before
    public void PetRepositoryIT.checkDataOnDemandHasInitializedCorrectly() {
        assertThat(getDod().getRandomPet())
            .as("Check data on demand for 'Pet' initializes correctly by getting a random Pet")
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.countShouldReturnExpectedValue() {
        // Verify
        assertThat(getRepository().count()).as("Check there are available 'Pet' entries").isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.findOneShouldReturnExistingPet() {
        // Setup
        Long id = getRandomPetId();
        
        // Exercise
        Pet pet = getRepository().findOne(id);
        
        // Verify
        assertThat(pet).as("Check that findOne illegally returned null for id %s", id).isNotNull();
        assertThat(id).as("Check the identifier of the found 'Pet' is the same used to look for it")
            .isEqualTo(pet.getId());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.findAllShouldReturnAllPets() {
        // Setup
        assertThat(getRepository().count())
            .as("Check the number of entries is not too big (250 entries). "
                + "If it is, please review the tests so it doesn't take too long to run them")
            .isLessThan(250);
        
        // Exercise
        List<Pet> result = getRepository().findAll();
        
        // Verify
        assertThat(result).as("Check 'findAll' returns a not null list of entries").isNotNull();
        assertThat(result.size()).as("Check 'findAll' returns a not empty list of entries")
            .isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.persistShouldGenerateIdValue() {
        // Setup
        // Exercise
        Pet pet = getDod().getNewRandomTransientPet();
        
        // Verify
        assertThat(pet).as("Check the Data on demand generated a new non null 'Pet'").isNotNull();
        assertThat(pet.getId()).as("Check the Data on demand generated a new 'Pet' whose id is null")
            .isNull();
        try {
            pet = getRepository().saveAndFlush(pet);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter
                .hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".")
                    .append(cv.getPropertyPath()).append(": ").append(cv.getMessage())
                    .append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        assertThat(pet.getId()).as("Check a 'Pet' (%s) id is not null after been persisted", pet)
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.deleteShouldMakePetUnavailable() {
        // Setup
        Long id = getRandomPetId();
        Pet pet = getRepository().findOne(id);
        
        // Exercise
        getRepository().delete(pet);
        
        // Verify
        assertThat(getRepository().findOne(id))
        .as("Check the deleted 'Pet' %s is no longer available with 'findOne'", pet).isNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.findAllCustomNotFilteredNotPagedShouldReturnAllPets() {
        // Exercise
        Page<Pet> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, getDod().getSize()));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check 'findAll' with null 'GlobalSearch' and no pagination returns all entries")
            .isEqualTo(getDod().getSize());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void PetRepositoryIT.findAllCustomNotFilteredPagedShouldReturnAPetsPage() {
        // Exercise
        Page<Pet> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, 3));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check result number is not greater than the page size").isLessThanOrEqualTo(3);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    private Long PetRepositoryIT.getRandomPetId() {
        Pet pet = getDod().getRandomPet();
        Long id = pet.getId();
        assertThat(id).as("Check the Data on demand generated a 'Pet' with an identifier").isNotNull();
        return id;
    }
    
}
