// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.jcagarcia.proof.tests.repository;

import io.github.jcagarcia.proof.tests.model.domain.Library;
import io.github.jcagarcia.proof.tests.repository.LibraryRepository;
import io.github.jcagarcia.proof.tests.repository.LibraryRepositoryCustom;
import io.springlets.data.jpa.repository.DetachableJpaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LibraryRepository_Roo_Jpa_Repository {
    
    declare parents: LibraryRepository extends DetachableJpaRepository<Library, Long>;
    
    declare parents: LibraryRepository extends LibraryRepositoryCustom;
    
    declare @type: LibraryRepository: @Transactional(readOnly = true);
    
}
