// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.repository;

import static org.assertj.core.api.Assertions.assertThat;

import io.springlets.data.domain.GlobalSearch;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.roo.petclinic.config.SpringDataJpaDetachableRepositoryConfiguration;
import org.springframework.roo.petclinic.dod.DataOnDemandConfiguration;
import org.springframework.roo.petclinic.domain.Visit;
import org.springframework.roo.petclinic.domain.dod.VisitDataOnDemand;
import org.springframework.roo.petclinic.repository.VisitRepository;
import org.springframework.roo.petclinic.repository.VisitRepositoryIT;
import org.springframework.test.context.junit4.SpringRunner;

privileged aspect VisitRepositoryIT_Roo_RepositoryJpaIntegrationTest {
    
    declare @type: VisitRepositoryIT: @RunWith(SpringRunner.class);
    
    declare @type: VisitRepositoryIT: @DataJpaTest;
    
    declare @type: VisitRepositoryIT: @Import({ DataOnDemandConfiguration.class, SpringDataJpaDetachableRepositoryConfiguration.class });
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Rule
    public ExpectedException VisitRepositoryIT.thrown = ExpectedException.none();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private VisitRepository VisitRepositoryIT.repository;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private VisitDataOnDemand VisitRepositoryIT.dod;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitRepository
     */
    public VisitRepository VisitRepositoryIT.getRepository() {
        return repository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitDataOnDemand
     */
    public VisitDataOnDemand VisitRepositoryIT.getDod() {
        return dod;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Before
    public void VisitRepositoryIT.checkDataOnDemandHasInitializedCorrectly() {
        assertThat(getDod().getRandomVisit())
            .as("Check data on demand for 'Visit' initializes correctly by getting a random Visit")
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.countShouldReturnExpectedValue() {
        // Verify
        assertThat(getRepository().count()).as("Check there are available 'Visit' entries").isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.findOneShouldReturnExistingVisit() {
        // Setup
        Long id = getRandomVisitId();
        
        // Exercise
        Visit visit = getRepository().findOne(id);
        
        // Verify
        assertThat(visit).as("Check that findOne illegally returned null for id %s", id).isNotNull();
        assertThat(id).as("Check the identifier of the found 'Visit' is the same used to look for it")
            .isEqualTo(visit.getId());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.findAllShouldReturnAllVisits() {
        // Setup
        assertThat(getRepository().count())
            .as("Check the number of entries is not too big (250 entries). "
                + "If it is, please review the tests so it doesn't take too long to run them")
            .isLessThan(250);
        
        // Exercise
        List<Visit> result = getRepository().findAll();
        
        // Verify
        assertThat(result).as("Check 'findAll' returns a not null list of entries").isNotNull();
        assertThat(result.size()).as("Check 'findAll' returns a not empty list of entries")
            .isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.persistShouldGenerateIdValue() {
        // Setup
        // Exercise
        Visit visit = getDod().getNewRandomTransientVisit();
        
        // Verify
        assertThat(visit).as("Check the Data on demand generated a new non null 'Visit'").isNotNull();
        assertThat(visit.getId()).as("Check the Data on demand generated a new 'Visit' whose id is null")
            .isNull();
        try {
            visit = getRepository().saveAndFlush(visit);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter
                .hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".")
                    .append(cv.getPropertyPath()).append(": ").append(cv.getMessage())
                    .append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        assertThat(visit.getId()).as("Check a 'Visit' (%s) id is not null after been persisted", visit)
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.deleteShouldMakeVisitUnavailable() {
        // Setup
        Long id = getRandomVisitId();
        Visit visit = getRepository().findOne(id);
        
        // Exercise
        getRepository().delete(visit);
        
        // Verify
        assertThat(getRepository().findOne(id))
        .as("Check the deleted 'Visit' %s is no longer available with 'findOne'", visit).isNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.findAllCustomNotFilteredNotPagedShouldReturnAllVisits() {
        // Exercise
        Page<Visit> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, getDod().getSize()));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check 'findAll' with null 'GlobalSearch' and no pagination returns all entries")
            .isEqualTo(getDod().getSize());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void VisitRepositoryIT.findAllCustomNotFilteredPagedShouldReturnAVisitsPage() {
        // Exercise
        Page<Visit> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, 3));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check result number is not greater than the page size").isLessThanOrEqualTo(3);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    private Long VisitRepositoryIT.getRandomVisitId() {
        Visit visit = getDod().getRandomVisit();
        Long id = visit.getId();
        assertThat(id).as("Check the Data on demand generated a 'Visit' with an identifier").isNotNull();
        return id;
    }
    
}
