// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.jcagarcia.proof.tests.config.jackson;

import com.fasterxml.jackson.databind.module.SimpleModule;
import io.github.jcagarcia.proof.tests.config.jackson.DomainModelModule;
import io.github.jcagarcia.proof.tests.domain.Book;
import io.github.jcagarcia.proof.tests.web.BookJsonMixin;
import org.springframework.boot.jackson.JsonComponent;

privileged aspect DomainModelModule_Roo_DomainModelModule {
    
    declare parents: DomainModelModule extends SimpleModule;
    
    declare @type: DomainModelModule: @JsonComponent;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     */
    public DomainModelModule.new() {
        // Mixin registration
        
        setMixInAnnotation(Book.class, BookJsonMixin.class);
    }

}
