// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.repository;

import io.springlets.data.jpa.repository.DetachableJpaRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.roo.petclinic.domain.Owner;
import org.springframework.roo.petclinic.domain.Pet;
import org.springframework.roo.petclinic.domain.reference.PetType;
import org.springframework.roo.petclinic.repository.PetRepository;
import org.springframework.roo.petclinic.repository.PetRepositoryCustom;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PetRepository_Roo_Jpa_Repository {
    
    declare parents: PetRepository extends DetachableJpaRepository<Pet, Long>;
    
    declare parents: PetRepository extends PetRepositoryCustom;
    
    declare @type: PetRepository: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param owner
     * @return Long
     */
    public abstract long PetRepository.countByOwner(Owner owner);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param owner
     * @param pageable
     * @return Page
     */
    public abstract Page<Pet> PetRepository.findByOwner(Owner owner, Pageable pageable);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param sendReminders
     * @param weight
     * @param pageable
     * @return Page
     */
    public abstract Page<Pet> PetRepository.findBySendRemindersAndWeightLessThan(boolean sendReminders, Float weight, Pageable pageable);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param sendReminders
     * @param weight
     * @return Long
     */
    public abstract long PetRepository.countBySendRemindersAndWeightLessThan(boolean sendReminders, Float weight);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param type
     * @param name
     * @param pageable
     * @return Page
     */
    public abstract Page<Pet> PetRepository.findByTypeAndNameLike(PetType type, String name, Pageable pageable);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param type
     * @param name
     * @return Long
     */
    public abstract long PetRepository.countByTypeAndNameLike(PetType type, String name);
    
}
