// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.repository;

import com.querydsl.core.types.Path;
import com.querydsl.core.types.Projections;
import com.querydsl.jpa.JPQLQuery;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.data.jpa.repository.support.QueryDslRepositorySupportExt.AttributeMappingBuilder;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.roo.petclinic.domain.QVet;
import org.springframework.roo.petclinic.domain.Vet;
import org.springframework.roo.petclinic.domain.VetInfo;
import org.springframework.roo.petclinic.repository.VetRepositoryCustom;
import org.springframework.roo.petclinic.repository.VetRepositoryImpl;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VetRepositoryImpl_Roo_Jpa_Repository_Impl {
    
    declare parents: VetRepositoryImpl implements VetRepositoryCustom;
    
    declare @type: VetRepositoryImpl: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.FIRST_NAME = "firstName";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.LAST_NAME = "lastName";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.ADDRESS = "address";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.CITY = "city";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.TELEPHONE = "telephone";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.HOME_PAGE = "homePage";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.EMAIL = "email";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.BIRTH_DAY = "birthDay";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.EMPLOYED_SINCE = "employedSince";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.SPECIALTY = "specialty";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.CREATED_DATE = "createdDate";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.CREATED_BY = "createdBy";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.MODIFIED_DATE = "modifiedDate";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.MODIFIED_BY = "modifiedBy";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String VetRepositoryImpl.ID = "id";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<VetInfo> VetRepositoryImpl.findAll(GlobalSearch globalSearch, Pageable pageable) {
        
        QVet vet = QVet.vet;
        
        JPQLQuery<Vet> query = from(vet);
        
        Path<?>[] paths = new Path<?>[] {vet.id,vet.firstName,vet.lastName,vet.specialty};        
        applyGlobalSearch(globalSearch, query, paths);
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(ID, vet.id)
			.map(FIRST_NAME, vet.firstName)
			.map(LAST_NAME, vet.lastName)
			.map(SPECIALTY, vet.specialty);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, Projections.constructor(VetInfo.class, vet.id, vet.firstName, vet.lastName, vet.specialty ));
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<VetInfo> VetRepositoryImpl.findAllByIdsIn(List<Long> ids, GlobalSearch globalSearch, Pageable pageable) {
        
        QVet vet = QVet.vet;
        
        JPQLQuery<Vet> query = from(vet);
        
        Path<?>[] paths = new Path<?>[] {vet.id,vet.firstName,vet.lastName,vet.specialty};        
        applyGlobalSearch(globalSearch, query, paths);
        
        // Also, filter by the provided ids
        query.where(vet.id.in(ids));
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(ID, vet.id)
			.map(FIRST_NAME, vet.firstName)
			.map(LAST_NAME, vet.lastName)
			.map(SPECIALTY, vet.specialty);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, Projections.constructor(VetInfo.class, vet.id, vet.firstName, vet.lastName, vet.specialty ));
    }
    
}
