// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.web;

import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.roo.petclinic.domain.dod.PetFactory;
import org.springframework.roo.petclinic.service.api.PetService;
import org.springframework.roo.petclinic.web.PetsItemJsonController;
import org.springframework.roo.petclinic.web.PetsItemJsonControllerIT;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect PetsItemJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    declare @type: PetsItemJsonControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: PetsItemJsonControllerIT: @SpringletsWebMvcTest(controllers = PetsItemJsonController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc PetsItemJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private PetService PetsItemJsonControllerIT.petService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private PetFactory PetsItemJsonControllerIT.factory = new PetFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc PetsItemJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetService
     */
    public PetService PetsItemJsonControllerIT.getPetService() {
        return petService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param petService
     */
    public void PetsItemJsonControllerIT.setPetService(PetService petService) {
        this.petService = petService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetFactory
     */
    public PetFactory PetsItemJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void PetsItemJsonControllerIT.setFactory(PetFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void PetsItemJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
