// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.web;

import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.roo.petclinic.domain.dod.VetFactory;
import org.springframework.roo.petclinic.service.api.VetService;
import org.springframework.roo.petclinic.service.api.VisitService;
import org.springframework.roo.petclinic.web.VetsCollectionThymeleafController;
import org.springframework.roo.petclinic.web.VetsCollectionThymeleafControllerIT;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect VetsCollectionThymeleafControllerIT_Roo_ThymeleafControllerIntegrationTest {
    
    declare @type: VetsCollectionThymeleafControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: VetsCollectionThymeleafControllerIT: @SpringletsWebMvcTest(controllers = VetsCollectionThymeleafController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc VetsCollectionThymeleafControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private VetService VetsCollectionThymeleafControllerIT.vetServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private VisitService VetsCollectionThymeleafControllerIT.visitServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private VetFactory VetsCollectionThymeleafControllerIT.factory = new VetFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc VetsCollectionThymeleafControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VetService
     */
    public VetService VetsCollectionThymeleafControllerIT.getVetServiceService() {
        return vetServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param vetServiceService
     */
    public void VetsCollectionThymeleafControllerIT.setVetServiceService(VetService vetServiceService) {
        this.vetServiceService = vetServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitService
     */
    public VisitService VetsCollectionThymeleafControllerIT.getVisitServiceService() {
        return visitServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param visitServiceService
     */
    public void VetsCollectionThymeleafControllerIT.setVisitServiceService(VisitService visitServiceService) {
        this.visitServiceService = visitServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VetFactory
     */
    public VetFactory VetsCollectionThymeleafControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void VetsCollectionThymeleafControllerIT.setFactory(VetFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void VetsCollectionThymeleafControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
