// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the extended .java class if you wish to edit any member(s).
package io.github.jcagarcia.proofs.springroonoaspectjava.service.api;

import io.github.jcagarcia.proofs.springroonoaspectjava.model.Pet;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.format.EntityResolver;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface PetService_ROO extends EntityResolver<Pet, Long> {

    // DO NOT EDIT THIS CODE. THIS CODE IS MANAGED BY THE
    // @RooService ANNOTATION

    /**
     * TODO Auto-generated method documentation
     *
     * @param id
     * @return Pet
     */
    Pet findOne(Long id);

    /**
     * TODO Auto-generated method documentation
     *
     * @param Pet
     */
    void delete(Pet Pet);

    /**
     * TODO Auto-generated method documentation
     *
     * @param entities
     * @return List
     */
    List<Pet> save(Iterable<Pet> entities);

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     */
    void delete(Iterable<Long> ids);

    /**
     * TODO Auto-generated method documentation
     *
     * @param entity
     * @return Pet
     */
    Pet save(Pet entity);

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     * @return List
     */
    List<Pet> findAll(Iterable<Long> ids);

    /**
     * TODO Auto-generated method documentation
     *
     * @return List
     */
    List<Pet> findAll();

    /**
     * TODO Auto-generated method documentation
     *
     * @return Long
     */
    long count();

    /**
     * TODO Auto-generated method documentation
     *
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    Page<Pet> findAll(GlobalSearch globalSearch, Pageable pageable);

    /**
     * TODO Auto-generated method documentation
     *
     * @param ids
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    Page<Pet> findAllByIdsIn(List<Long> ids, GlobalSearch globalSearch, Pageable pageable);

}
