// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the extended .java class if you wish to edit any member(s).
package io.github.jcagarcia.proofs.springroonoaspectjava.repository;

import io.github.jcagarcia.proofs.springroonoaspectjava.model.Pet;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.data.jpa.repository.support.QueryDslRepositorySupportExt;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Transactional(readOnly = true)
public class PetRepositoryImpl_ROO extends QueryDslRepositorySupportExt<Pet> implements PetRepositoryCustom {

    // DO NOT EDIT THIS CODE. THIS CODE IS MANAGED BY THE
    // @RooJpaRepositoryCustomImpl ANNOTATION

    public PetRepositoryImpl_ROO() {
        super(Pet.class);
    }

    @Override
    public Page<Pet> findAll(GlobalSearch search, Pageable pageable) {
        // TODO: Include QueryDSL maven plugin dependency
        return null;
    }

    @Override
    public Page<Pet> findAllByIdsIn(List<Long> ids, GlobalSearch search, Pageable pageable) {
        // TODO: Include QueryDSL maven plugin dependency
        return null;
    }



}
